import Head from 'next/head';
import styles from '@/styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Tai's App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div>
          <h1 style={{ fontSize: '3em', textAlign: 'center' }}>
            Welcome to Tai's App
          </h1>
          <h3 style={{ textAlign: 'center', marginTop: '1rem' }}>
            We offer multiple fun short courses
          </h3>
          <div style={{ marginTop: '1.5rem' }}>
            <h3>Courses:</h3>
            <h3>Locations:</h3>
            <h3>Scholarships:</h3>
          </div>
        </div>
      </main>
    </>
  );
}
